branch-defaults:
  master:
    environment: EB-Rahul-Demo2-dev
global:
  application_name: EB_Rahul_Demo2
  branch: null
  default_ec2_keyname: Rahul_KeyPair
  default_platform: Java 8 running on 64bit Amazon Linux
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
deploy:
        #artifact: target/demo-0.0.1-SNAPSHOT.jar 
        artifact:  /root/WiproCloud/Meru_CaseStudy/InventoryService/target/InventoryService-0.0.1-SNAPSHOT-exec.jar 
